/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Draw_OOP;

import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.JColorChooser;
import javax.swing.event.UndoableEditEvent;
import javax.swing.undo.AbstractUndoableEdit;
import javax.swing.undo.CannotRedoException;
import javax.swing.undo.UndoManager;
import pplus_draw_simple.Draw1;

/**
 *
 * @author rs
 */
public class Draw extends javax.swing.JFrame {

    /**
     * Creates new form Draw
     */
    public Draw() {

        initComponents();
        checkChoose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanelDRAW = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        JREC = new javax.swing.JRadioButton();
        JSquare = new javax.swing.JRadioButton();
        JLine = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        edt_height = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        edt_weight = new javax.swing.JTextField();
        btn_set_color = new javax.swing.JToggleButton();
        btn_clear = new javax.swing.JButton();
        btn_undo = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelDRAW.setBackground(new java.awt.Color(254, 254, 254));
        jPanelDRAW.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelDRAWMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanelDRAWMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelDRAWMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelDRAWLayout = new javax.swing.GroupLayout(jPanelDRAW);
        jPanelDRAW.setLayout(jPanelDRAWLayout);
        jPanelDRAWLayout.setHorizontalGroup(
            jPanelDRAWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 501, Short.MAX_VALUE)
        );
        jPanelDRAWLayout.setVerticalGroup(
            jPanelDRAWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 432, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(220, 220, 220));

        buttonGroup1.add(JREC);
        JREC.setText("Rectangle");

        buttonGroup1.add(JSquare);
        JSquare.setText("Square");

        buttonGroup1.add(JLine);
        JLine.setText("Line");

        jLabel1.setText("Height");

        jLabel2.setText("Weight");

        btn_set_color.setText("Choose Color");
        btn_set_color.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_set_colorMouseClicked(evt);
            }
        });

        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        btn_undo.setText("Undo");
        btn_undo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_undoActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Fill");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(edt_weight)
                        .addComponent(edt_height)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btn_clear)
                    .addComponent(btn_undo)
                    .addComponent(JREC)
                    .addComponent(JSquare)
                    .addComponent(JLine)
                    .addComponent(btn_set_color)
                    .addComponent(jCheckBox1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JREC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JSquare)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLine)
                .addGap(63, 63, 63)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edt_height, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(5, 5, 5)
                .addComponent(edt_weight, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_set_color)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_undo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_clear)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelDRAW, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelDRAW, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Graphics2D gr2;

    Shape shape;
    List<Shape> arrShape = new ArrayList<Shape>() {
    };
    int Height;
    int Width;

    private void checkChoose() {
        if (JREC.isSelected()) {
            edt_height.setEnabled(true);
            edt_weight.setEnabled(true);

        }
        if (JSquare.isSelected()) {
            edt_weight.setEnabled(false);

        }
    }
    private UndoManager undoManager = new UndoManager();

    private void jPanelDRAWMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelDRAWMouseReleased
        // TODO add your handling code here:
        this.Height = Integer.parseInt(edt_height.getText().toString());
        this.Width = Integer.parseInt(edt_weight.getText().toString());

        RenderingHints rh = new RenderingHints(RenderingHints.KEY_ANTIALIASING,
                RenderingHints.VALUE_ANTIALIAS_ON);
        rh.put(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY);

        gr2.addRenderingHints(rh);

//        this.gr2 = (Graphics2D) image.getGraphics();
        if (JREC.isSelected()) {
            String name = "createRectangle";
            shape = ShapeMaker.createRectangle(startX, startY, this.Width, this.Height, sColor);
            draw();

        }
        if (JSquare.isSelected()) {
            shape = ShapeMaker.createSquare(startX, startY, this.Width, this.Height, sColor);
            draw();

        }
        if (JLine.isSelected()) {
            shape = ShapeMaker.createLine(startX, startY, this.Width, this.Height, sColor);
            draw();

        }


    }//GEN-LAST:event_jPanelDRAWMouseReleased

    private void jPanelDRAWMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelDRAWMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanelDRAWMouseClicked
    int startX, startY;


    private void jPanelDRAWMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelDRAWMousePressed
        // TODO add your handling code here:
        if (gr2 == null) {
            gr2 = (Graphics2D) jPanelDRAW.getGraphics();
        }
        startX = evt.getX();
        startY = evt.getY();

        //Set position for cursor

    }//GEN-LAST:event_jPanelDRAWMousePressed
    Color sColor;
    private void btn_set_colorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_set_colorMouseClicked
        // TODO add your handling code here:
        sColor = JColorChooser.showDialog(Draw.this,
                "Choose Color", sColor);


    }//GEN-LAST:event_btn_set_colorMouseClicked

    private void btn_undoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_undoActionPerformed
        if (!arrShape.isEmpty()) {
            int size = arrShape.size() - 1;
            arrShape.remove(size);
            jPanelDRAW.update(gr2);
            draw_all();
        }


    }//GEN-LAST:event_btn_undoActionPerformed
    private void draw() {
        shape.draw(gr2);
        arrShape.add(shape);
        draw_all();
    }

    public void draw_all() {
        for (int i = 0; i < arrShape.size(); i++) {
            Shape s = arrShape.get(i);
            s.draw(gr2);
        }
    }
    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        jPanelDRAW.update(gr2);
    }//GEN-LAST:event_btn_clearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Draw.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Draw.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Draw.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Draw.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Draw().setVisible(true);
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton JLine;
    private javax.swing.JRadioButton JREC;
    private javax.swing.JRadioButton JSquare;
    private javax.swing.JButton btn_clear;
    private javax.swing.JToggleButton btn_set_color;
    private javax.swing.JButton btn_undo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField edt_height;
    private javax.swing.JTextField edt_weight;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelDRAW;
    // End of variables declaration//GEN-END:variables

}
