/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pplus_draw_simple;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.geom.Ellipse2D;
import java.awt.geom.Line2D;
import java.awt.geom.Rectangle2D;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JColorChooser;

/**
 *
 * @author rs
 */
public class Draw extends javax.swing.JFrame {

    /**
     * Creates new form Draw
     */
    public Draw() {
        initComponents();
    }

    private int startX;
    private int startY;
    private int endX;
    private int endY;

    private Line2D lineBuffer;
    private Ellipse2D circBuffer;
    private Rectangle2D recBuffer;
    private Graphics g;
    private Graphics2D gr2 = (Graphics2D) g  ;
    private List<Line2D> listLine = new ArrayList();
    private List<Ellipse2D> listCric = new ArrayList();
    private List<Rectangle2D> listRec = new ArrayList();
    private ArrayList<Color> color = new ArrayList();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioGroup = new javax.swing.ButtonGroup();
        JRadioLine = new javax.swing.JRadioButton();
        jPanel_Draw = new javax.swing.JPanel();
        JRadioCricle = new javax.swing.JRadioButton();
        btn_clear = new javax.swing.JButton();
        jRadioSquare = new javax.swing.JRadioButton();
        jRadioRec = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        radioGroup.add(JRadioLine);
        JRadioLine.setText("Line");

        jPanel_Draw.setBackground(new java.awt.Color(254, 254, 254));
        jPanel_Draw.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel_DrawMouseDragged(evt);
            }
        });
        jPanel_Draw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel_DrawMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel_DrawMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel_DrawLayout = new javax.swing.GroupLayout(jPanel_Draw);
        jPanel_Draw.setLayout(jPanel_DrawLayout);
        jPanel_DrawLayout.setHorizontalGroup(
            jPanel_DrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 443, Short.MAX_VALUE)
        );
        jPanel_DrawLayout.setVerticalGroup(
            jPanel_DrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        radioGroup.add(JRadioCricle);
        JRadioCricle.setText("Cricle");

        btn_clear.setText("Clear");
        btn_clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_clearMouseClicked(evt);
            }
        });

        radioGroup.add(jRadioSquare);
        jRadioSquare.setText("Square");

        radioGroup.add(jRadioRec);
        jRadioRec.setText("Rectangle");

        jButton1.setText("Choose Color");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JRadioLine)
                    .addComponent(JRadioCricle)
                    .addComponent(jRadioSquare)
                    .addComponent(jRadioRec)
                    .addComponent(btn_clear)
                    .addComponent(jButton1))
                .addGap(45, 45, 45)
                .addComponent(jPanel_Draw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JRadioLine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JRadioCricle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioSquare)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioRec)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_clear)
                .addContainerGap(177, Short.MAX_VALUE))
            .addComponent(jPanel_Draw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel_DrawMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_DrawMousePressed
        // TODO add your handling code here:
        if (gr2 == null) {
            gr2 = (Graphics2D) jPanel_Draw.getGraphics();
        }

        //Set position for cursor
        startX = evt.getX();
        startY = evt.getY();
        endX = evt.getX();
        endY = evt.getY();
    }//GEN-LAST:event_jPanel_DrawMousePressed


    private void jPanel_DrawMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_DrawMouseDragged
        // TODO add your handling code here:
        if (JRadioLine.isSelected()) {
            jPanel_Draw.update(gr2);
            
            endX = evt.getX();
            endY = evt.getY();

            lineBuffer = new Line2D.Float(
                    (float) startX,
                    (float) startY,
                    (float) endX,
                    (float) endY);

            //Draw Line
            Draw_All();
            gr2.draw(lineBuffer);

        }
        if (JRadioCricle.isSelected()) {
            jPanel_Draw.update(gr2);

            endX = evt.getX() - startX;
            endY = evt.getY() - startY;

            circBuffer = new Ellipse2D.Float((float) startX,
                    (float) startY,
                    (float) endX,
                    (float) endY);
            //Draw Line
            
            Draw_All();
            gr2.setPaint(scolor);
            gr2.draw(circBuffer);
        }
        
        if (jRadioRec.isSelected()) {

            jPanel_Draw.update(gr2);

            endX = evt.getX() - startX;
            endY = evt.getY() - startY;

            recBuffer = new Rectangle2D.Float((float) startX,
                    (float) startY,
                    (float) endX,
                    (float) endY);

            //Draw Line
            Draw_All();
            gr2.draw(recBuffer);
        }


    }//GEN-LAST:event_jPanel_DrawMouseDragged

    private void jPanel_DrawMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_DrawMouseReleased
        // TODO add your handling code here:
        if (JRadioLine.isSelected()) {
            jPanel_Draw.update(gr2);

            endX = evt.getX();
            endY = evt.getY();

            lineBuffer = new Line2D.Float(
                    (float) startX,
                    (float) startY,
                    (float) endX,
                    (float) endY);
            //Draw Line
            listLine.add(lineBuffer);
            Draw_All();
        }
        if (JRadioCricle.isSelected()) {
            jPanel_Draw.update(gr2);

            endX = evt.getX() - startX;
            endY = evt.getY() - startY;

            circBuffer = new Ellipse2D.Float(
                    (float) startX,
                    (float) startY,
                    (float) endX,
                    (float) endY);
            //Draw Line
            listCric.add(circBuffer);
            Draw_All();
        }
        if (jRadioRec.isSelected()) {
            jPanel_Draw.update(gr2);

            endX = evt.getX() - startX;
            endY = evt.getY() - startY;

            recBuffer = new Rectangle2D.Float(
                    (float) startX,
                    (float) startY,
                    (float) endX,
                    (float) endY);
            //Draw Line
            listRec.add(recBuffer);
            Draw_All();
        }

    }//GEN-LAST:event_jPanel_DrawMouseReleased

    private void btn_clearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clearMouseClicked
        //update Frame
        jPanel_Draw.update(gr2);
        //Uncheck Radio Button
        listCric.clear();
        listLine.clear();
        listRec.clear();
    }//GEN-LAST:event_btn_clearMouseClicked
    Color scolor;
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        scolor = JColorChooser.showDialog(
                Draw.this,
                "Choose Color", scolor);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Draw_All() {
        for (int i = 0; i < listLine.size(); i++) {
            gr2.draw(listLine.get(i));
        }
        for (int i = 0; i < listCric.size(); i++) {
            gr2.draw(listCric.get(i));
        }
        for (int i = 0; i < listRec.size(); i++) {
            gr2.draw(listRec.get(i));
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Draw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Draw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Draw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Draw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Draw().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton JRadioCricle;
    private javax.swing.JRadioButton JRadioLine;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel_Draw;
    private javax.swing.JRadioButton jRadioRec;
    private javax.swing.JRadioButton jRadioSquare;
    private javax.swing.ButtonGroup radioGroup;
    // End of variables declaration//GEN-END:variables
}
