/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pplus_draw_simple;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

import javax.swing.JColorChooser;

/**
 *
 * @author rs
 */
public class Draw1 extends javax.swing.JFrame {

    /**
     * Creates new form Draw
     */
    public Draw1() {
        initComponents();
    }

    private int startX;
    private int startY;

    private Graphics g;
    private Graphics2D gr2 = (Graphics2D) g;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioGroup = new javax.swing.ButtonGroup();
        JRadioLine = new javax.swing.JRadioButton();
        jPanel_Draw = new javax.swing.JPanel();
        JRadioRound = new javax.swing.JRadioButton();
        btn_clear = new javax.swing.JButton();
        jRadioSquare = new javax.swing.JRadioButton();
        jRadioRec = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        triangle = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        radioGroup.add(JRadioLine);
        JRadioLine.setText("Line");

        jPanel_Draw.setBackground(new java.awt.Color(254, 254, 254));
        jPanel_Draw.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel_DrawMouseDragged(evt);
            }
        });
        jPanel_Draw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel_DrawMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel_DrawMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel_DrawLayout = new javax.swing.GroupLayout(jPanel_Draw);
        jPanel_Draw.setLayout(jPanel_DrawLayout);
        jPanel_DrawLayout.setHorizontalGroup(
            jPanel_DrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 458, Short.MAX_VALUE)
        );
        jPanel_DrawLayout.setVerticalGroup(
            jPanel_DrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        radioGroup.add(JRadioRound);
        JRadioRound.setText("Round");

        btn_clear.setText("Clear");
        btn_clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_clearMouseClicked(evt);
            }
        });

        radioGroup.add(jRadioSquare);
        jRadioSquare.setText("Square");

        radioGroup.add(jRadioRec);
        jRadioRec.setText("Rectangle");

        jButton1.setText("Choose Color");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        radioGroup.add(triangle);
        triangle.setText("Triangle");
        triangle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                triangleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JRadioLine)
                    .addComponent(JRadioRound)
                    .addComponent(jRadioSquare)
                    .addComponent(jRadioRec)
                    .addComponent(btn_clear)
                    .addComponent(jButton1)
                    .addComponent(triangle))
                .addGap(30, 30, 30)
                .addComponent(jPanel_Draw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JRadioLine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JRadioRound)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioSquare)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioRec)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(triangle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_clear)
                .addGap(32, 32, 32))
            .addComponent(jPanel_Draw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel_DrawMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_DrawMousePressed
        // TODO add your handling code here:
        if (gr2 == null) {
            gr2 = (Graphics2D) jPanel_Draw.getGraphics();
        }

        //Set position for cursor
        startX = evt.getX();
        startY = evt.getY();

    }//GEN-LAST:event_jPanel_DrawMousePressed


    private void jPanel_DrawMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_DrawMouseDragged

    }//GEN-LAST:event_jPanel_DrawMouseDragged


    private void jPanel_DrawMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_DrawMouseReleased
        // TODO add your handling code here:

        RenderingHints rh = new RenderingHints(RenderingHints.KEY_ANTIALIASING,
                RenderingHints.VALUE_ANTIALIAS_ON);
        rh.put(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY);
        
        gr2.setRenderingHints(rh);

        if (JRadioLine.isSelected()) {
            gr2.setColor(scolor);
            gr2.drawLine(startX, startY, startX + 200, startY);
        }
        if (JRadioRound.isSelected()) {
            gr2.setColor(scolor);

            gr2.drawOval(startX, startY, 80, 80);
        }
        if (jRadioSquare.isSelected()) {
            gr2.setColor(scolor);

            gr2.drawRect(startX, startY, 100, 100);
        }
        if (jRadioRec.isSelected()) {
            gr2.setColor(scolor);

            gr2.drawRect(startX, startY, 150, 80);
        }

        if (triangle.isSelected()) {
            gr2.setColor(scolor);

            try {
                int[] xDraw = {startX - 40, startX, startX + 40};
                int[] yDraw = {startY + 100, startY, startY + 100};

                gr2.drawPolygon(xDraw, yDraw, 3);

            } catch (Exception e) {
                System.err.println(e);

            }
        }

    }//GEN-LAST:event_jPanel_DrawMouseReleased

    private void btn_clearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clearMouseClicked
        jPanel_Draw.update(gr2);

    }//GEN-LAST:event_btn_clearMouseClicked
    Color scolor;
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        scolor = JColorChooser.showDialog(Draw1.this,
                "Choose Color", scolor);
    }//GEN-LAST:event_jButton1MouseClicked

    private void triangleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_triangleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_triangleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Draw1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Draw1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Draw1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Draw1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Draw1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton JRadioLine;
    private javax.swing.JRadioButton JRadioRound;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel_Draw;
    private javax.swing.JRadioButton jRadioRec;
    private javax.swing.JRadioButton jRadioSquare;
    private javax.swing.ButtonGroup radioGroup;
    private javax.swing.JRadioButton triangle;
    // End of variables declaration//GEN-END:variables
}
